PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

DROP TABLE IF EXISTS manager;
CREATE TABLE manager (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE, name VARCHAR (32), type_user VARCHAR (32));

DROP TABLE IF EXISTS buyer;
CREATE TABLE buyer (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE, name VARCHAR (32), type_user VARCHAR (32));

DROP TABLE IF EXISTS other_personal;
CREATE TABLE other_personal (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE, name VARCHAR (32), type_user VARCHAR (32));

DROP TABLE IF EXISTS category;
CREATE TABLE category (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE, name VARCHAR (32), category VARCHAR (32));

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;